---
name: virtualbidapp
description: aplicativo dedicado a ventas
publish_to: none
version: 1.0.0+15
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  font_awesome_flutter: ^8.8.1
  http: ^0.12.2
  youtube_player_flutter: ^7.0.0+7
  table_calendar: ^2.2.3
  intl: ^0.16.1
  cloud_firestore: ^0.14.0+2
  firebase_auth: ^0.18.0+1
  provider: ^4.3.2+2
  flutter_auth_buttons: ^0.10.0
  firebase_helpers: ^0.2.1
  path_provider: ^1.6.14
  flutter_inappwebview: ^4.0.0+4
  flutter_youtube_view: ^1.1.9
  after_layout: ^1.0.7+2
  firebase_messaging: ^7.0.0
  firebase_storage: ^4.0.0
  image_picker: ^0.6.7+7
  uuid: ^2.2.2
  app_settings: ^4.0.3
  pdf_viewer_plugin: ^1.0.0+2
  auto_size_text: ^2.1.0
  firebase_core: ^0.5.0
  url_launcher: ^5.5.0
  shared_preferences: ^0.5.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^0.1.9
  flutter_launcher_icons: ^0.7.5
flutter_native_splash:
  image: assets/logo/logoxxxhdpi.png
  color: e1e2e1
  android: true
  ios: true
flutter_icons:
  android: launcher_icon
  ios: true
  image_path: assets/icon/virtualbidicon.png
  adaptative_icon_background: assets/icon/virtualbidicon.png
flutter:
  uses-material-design: true
  assets:
  - assets/img/
  - assets/logo/
  fonts:
  - family: Roboto
    fonts:
    - asset: assets/fonts/Roboto-Bold.ttf
      weight: 700
    - asset: assets/fonts/Roboto-Regular.ttf
      weight: 400
